
# Define services
services:

  # App Service

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379

  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ./data/dev/mongo:/data/db

